language: node_js
script:
  - make # ensure pkg builds
  - make test # run tests
  - make examples-test # ensure examples still build
  - make docs # ensure docs builds
after_success:
  - make ci-coverage-publish
